/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreesIdRouteImport } from './routes/trees.$id'

const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreesIdRoute = TreesIdRouteImport.update({
  id: '/trees/$id',
  path: '/trees/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mobile': typeof MobileRoute
  '/trees/$id': typeof TreesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mobile': typeof MobileRoute
  '/trees/$id': typeof TreesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mobile': typeof MobileRoute
  '/trees/$id': typeof TreesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mobile' | '/trees/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mobile' | '/trees/$id'
  id: '__root__' | '/' | '/mobile' | '/trees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MobileRoute: typeof MobileRoute
  TreesIdRoute: typeof TreesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trees/$id': {
      id: '/trees/$id'
      path: '/trees/$id'
      fullPath: '/trees/$id'
      preLoaderRoute: typeof TreesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MobileRoute: MobileRoute,
  TreesIdRoute: TreesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
