ALTER TABLE public.trees
  ADD COLUMN IF NOT EXISTS climate TEXT,
  ADD COLUMN IF NOT EXISTS foliage TEXT,
  ADD COLUMN IF NOT EXISTS style TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}';